/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ordemservico.view;

import java.util.ArrayList;

/**
 *
 * @author aluno
 */
public class FrameAcessoTelas extends javax.swing.JFrame {

    /**
     * Creates new form FrameAcessoTelas
     */
    public FrameAcessoTelas() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btAcessoServico = new javax.swing.JButton();
        btAcessoVeiculo = new javax.swing.JButton();
        btGerarRelatorio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btAcessoCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btAcessoServico.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btAcessoServico.setText("Registrar Serviços");
        btAcessoServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAcessoServicoActionPerformed(evt);
            }
        });

        btAcessoVeiculo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btAcessoVeiculo.setText("Registrar Veículos");
        btAcessoVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAcessoVeiculoActionPerformed(evt);
            }
        });

        btGerarRelatorio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btGerarRelatorio.setText("Gerar Relatório");
        btGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerarRelatorioActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("ACESSOS:");

        btAcessoCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btAcessoCliente.setText("Registrar Cliente");
        btAcessoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAcessoClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btAcessoVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btAcessoServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btGerarRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btAcessoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(132, 132, 132))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(154, 154, 154))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btAcessoCliente)
                .addGap(35, 35, 35)
                .addComponent(btAcessoVeiculo)
                .addGap(34, 34, 34)
                .addComponent(btAcessoServico)
                .addGap(33, 33, 33)
                .addComponent(btGerarRelatorio)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAcessoServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcessoServicoActionPerformed
        this.dispose();
        
        FrameDadosServicos acessoDadosServicos = new FrameDadosServicos();
        acessoDadosServicos.setVisible(true);
    }//GEN-LAST:event_btAcessoServicoActionPerformed

    private void btGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerarRelatorioActionPerformed
        this.dispose();
        
        FrameRelatorio acessoRelatorio = new FrameRelatorio();
        acessoRelatorio.setVisible(true);
        
    }//GEN-LAST:event_btGerarRelatorioActionPerformed

    private void btAcessoVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcessoVeiculoActionPerformed
        this.dispose();
        
        FrameDadosVeiculos acessoDadosVeiculos = new FrameDadosVeiculos();
        acessoDadosVeiculos.setVisible(true);
    }//GEN-LAST:event_btAcessoVeiculoActionPerformed

    private void btAcessoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcessoClienteActionPerformed
        FrameDadosCliente acessoDadosCliente = new FrameDadosCliente();
        
        this.dispose();
        
        acessoDadosCliente.setVisible(true);
    }//GEN-LAST:event_btAcessoClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAcessoCliente;
    private javax.swing.JButton btAcessoServico;
    private javax.swing.JButton btAcessoVeiculo;
    private javax.swing.JButton btGerarRelatorio;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
