/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ordemservico.view;

import com.mycompany.ordemservico.controller.Controller;
import com.mycompany.ordemservico.model.Pecas;
import java.math.BigDecimal;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class FrameDadosPecas extends javax.swing.JFrame {

    /**
     * Creates new form FrameDadosPecas
     */
    public FrameDadosPecas() {
        initComponents();
        setLocationRelativeTo(this);
        Controller.listaPecas = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ckBloco = new javax.swing.JCheckBox();
        ckVelas = new javax.swing.JCheckBox();
        ckCaixa = new javax.swing.JCheckBox();
        ckPastilha = new javax.swing.JCheckBox();
        ckPistao = new javax.swing.JCheckBox();
        ckSuspensao = new javax.swing.JCheckBox();
        lbValorBloco = new javax.swing.JLabel();
        lbValorVelas = new javax.swing.JLabel();
        lbValorCambio = new javax.swing.JLabel();
        lbValorPastilha = new javax.swing.JLabel();
        lbPistao = new javax.swing.JLabel();
        lbSuspensao = new javax.swing.JLabel();
        spBloco = new javax.swing.JSpinner();
        spVelas = new javax.swing.JSpinner();
        spCaixa = new javax.swing.JSpinner();
        spPastilha = new javax.swing.JSpinner();
        spPistao = new javax.swing.JSpinner();
        spSuspensao = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        btCancelar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("PEÇAS UTILIZADAS");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("PEÇAS");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("QUANTIDADE");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("VALOR UNITÁRIO");

        ckBloco.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ckBloco.setText("Bloco do motor");
        ckBloco.setName("20"); // NOI18N

        ckVelas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ckVelas.setText("Velas de ignição");
        ckVelas.setName("85"); // NOI18N

        ckCaixa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ckCaixa.setText("Caixa de câmbio");
        ckCaixa.setName("200"); // NOI18N

        ckPastilha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ckPastilha.setText("Pastilha de Freio");
        ckPastilha.setName("125"); // NOI18N

        ckPistao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ckPistao.setText("Pistão");
        ckPistao.setName("15"); // NOI18N

        ckSuspensao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ckSuspensao.setText("Suspensão a Rosca");
        ckSuspensao.setName("105"); // NOI18N

        lbValorBloco.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbValorBloco.setText("R$ 20.00");

        lbValorVelas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbValorVelas.setText("R$ 85.00");

        lbValorCambio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbValorCambio.setText("R$ 200.00");

        lbValorPastilha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbValorPastilha.setText("R$ 125.00");

        lbPistao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbPistao.setText("R$ 15.00");

        lbSuspensao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbSuspensao.setText("R$ 105.00");

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addGap(114, 114, 114))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ckBloco)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(spBloco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(123, 123, 123))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ckSuspensao)
                                            .addComponent(ckPistao)
                                            .addComponent(ckPastilha)
                                            .addComponent(ckCaixa)
                                            .addComponent(ckVelas))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(spCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(spVelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(spPastilha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(spPistao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(spSuspensao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(123, 123, 123)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbValorVelas)
                                    .addComponent(lbValorBloco)
                                    .addComponent(jLabel4)
                                    .addComponent(lbValorCambio)
                                    .addComponent(lbValorPastilha)
                                    .addComponent(lbPistao)
                                    .addComponent(lbSuspensao)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(btCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btSalvar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckBloco)
                    .addComponent(lbValorBloco)
                    .addComponent(spBloco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckVelas)
                    .addComponent(lbValorVelas)
                    .addComponent(spVelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckCaixa)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbValorCambio)
                        .addComponent(spCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ckPastilha)
                        .addComponent(spPastilha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbValorPastilha))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckPistao)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbPistao)
                        .addComponent(spPistao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ckSuspensao)
                        .addComponent(lbSuspensao))
                    .addComponent(spSuspensao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btCancelar))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        dispose();
        
        FrameAcessoTelas acessoTela = new FrameAcessoTelas();
        acessoTela.setVisible(true);
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        int qtdBloco = (int) spBloco.getValue();
        int qtdCaixa = (int) spCaixa.getValue();
        int qtdPastilha = (int) spPastilha.getValue();
        int qtdPistao = (int) spPistao.getValue();
        int qtdSuspensao = (int) spSuspensao.getValue();
        int qtdVelas = (int) spVelas.getValue();
        
        double valorBloco = Double.parseDouble(ckBloco.getName());
        double valorCaixa = Double.parseDouble(ckCaixa.getName());
        double valorPastilha = Double.parseDouble(ckPastilha.getName());
        double valorPistao = Double.parseDouble(ckPistao.getName());
        double valorSuspensao = Double.parseDouble(ckSuspensao.getName());
        double valorVelas = Double.parseDouble(ckVelas.getName());
        
        Pecas peca = new Pecas();
        
        if (qtdBloco == 0 && qtdCaixa == 0 && qtdPastilha == 0 && qtdPistao == 0 && qtdSuspensao == 0 && qtdVelas == 0) {
            JOptionPane.showMessageDialog(this, "Você precisa definir a quantidade de peças!", "ERRO!", JOptionPane.ERROR_MESSAGE);
        } else {
            
            if (ckBloco.isSelected()) {
                peca.setNomePeca(ckBloco.getText());
                peca.setQtdPeca(qtdBloco);
                peca.setValorUnitario(BigDecimal.valueOf(valorBloco).multiply(BigDecimal.valueOf(qtdBloco)));
            }
            
            if (ckPastilha.isSelected()) {
                peca.setNomePeca(ckPastilha.getText());
                peca.setQtdPeca(qtdPastilha);
                peca.setValorUnitario(BigDecimal.valueOf(valorPastilha).multiply(BigDecimal.valueOf(qtdPastilha)));
            }
            
            if (ckCaixa.isSelected()) {
                peca.setNomePeca(ckCaixa.getText());
                peca.setQtdPeca(qtdCaixa);
                peca.setValorUnitario(BigDecimal.valueOf(valorCaixa).multiply(BigDecimal.valueOf(qtdCaixa)));
            }
            
            if (ckPistao.isSelected()) {
                peca.setNomePeca(ckPistao.getText());
                peca.setQtdPeca(qtdPistao);
                peca.setValorUnitario(BigDecimal.valueOf(valorPistao).multiply(BigDecimal.valueOf(qtdPistao)));
            }
            
            if (ckSuspensao.isSelected()) {
                peca.setNomePeca(ckSuspensao.getText());
                peca.setQtdPeca(qtdSuspensao);
                peca.setValorUnitario(BigDecimal.valueOf(valorSuspensao).multiply(BigDecimal.valueOf(qtdSuspensao)));
            }
            
            if (ckVelas.isSelected()) {
                peca.setNomePeca(ckVelas.getText());
                peca.setQtdPeca(qtdVelas);
                peca.setValorUnitario(BigDecimal.valueOf(valorVelas).multiply(BigDecimal.valueOf(qtdVelas)));
            }
            
            Controller.listaPecas.add(peca);
            
            System.out.println(peca.getValorUnitario());
            
             JOptionPane.showMessageDialog(null, "Peças cadastrada com Sucesso!");

            dispose();
            
            FrameAcessoTelas acessoTela = new FrameAcessoTelas();
            acessoTela.setVisible(true);
        }
    }//GEN-LAST:event_btSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JCheckBox ckBloco;
    private javax.swing.JCheckBox ckCaixa;
    private javax.swing.JCheckBox ckPastilha;
    private javax.swing.JCheckBox ckPistao;
    private javax.swing.JCheckBox ckSuspensao;
    private javax.swing.JCheckBox ckVelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbPistao;
    private javax.swing.JLabel lbSuspensao;
    private javax.swing.JLabel lbValorBloco;
    private javax.swing.JLabel lbValorCambio;
    private javax.swing.JLabel lbValorPastilha;
    private javax.swing.JLabel lbValorVelas;
    private javax.swing.JSpinner spBloco;
    private javax.swing.JSpinner spCaixa;
    private javax.swing.JSpinner spPastilha;
    private javax.swing.JSpinner spPistao;
    private javax.swing.JSpinner spSuspensao;
    private javax.swing.JSpinner spVelas;
    // End of variables declaration//GEN-END:variables
}
